### ISSUE TITLE
Question about behavior

### ISSUE THREAD

**Issue by talamaska** [kekland/croppy#1]
I haven't yet tried this package. Before i test it out I want to know one thing. When cropping, how is the result image cropped - from the original size of the image or from the screen size of the image. In the end I want to get best quality so it would be great if it is cropping from the original image.

P.S After looking at the demo again I now have more questions. 
1. Will be there a way to lock the coordinates of the cropping area
2. Conditional display of the corners
3. Custom form of the croppable area, by providing a path maybe?
4. Custom colors of the grid, corners, buttons, backgrounds?
5. enable/disable features? Like I may want to have only pinch to zoom, and pan, but not rotate and flip.
6. enable/disable grid? Maybe also provide a a way to pass a CustomPaint?

**Comment by kekland** [comment]
@talamaska Hi! Thanks for the questions:

The result image is cropped from the original size of the image using bilinear interpolation. In the future I might add other ways of pixel interpolation, but so far bilinear seems to work just fine. One potential pitfall is: Flutter's rasterization performance drops heavily with large images, so not yet sure how this can be tackled. In my experience, images below 2000x2000 are fine.

^ One potential solution would be to compress the image that we display on the screen, but keep a full-size image in the cache.

1. Not sure by what you mean by "locking the coordinates" - if the aim is to constrain the allowed crop area, this can be implemented with a custom `CroppableImageController`'s `normalize()` method. I'm not yet sure if this is a commonly used feature, so I will leave it up to the implementer to create it. But let me know if this is something that can be added to the default controllers.

3. Yes, definitely, this is something that I've planned to add soon. I'm thinking to provide a function (`Size -> Path`) to the `CroppableImageController` that can describe the path of the cropper handles.

2, 4, 5, 6. All of these can be customized by creating a custom `CroppableImageController` and widgets. There's already an implementation for iOS, but the plan is to make it easy to customize literally everything. I will add more documentation on this a bit later once everything is more-less stable (and once there's a Material implementation).

Let me know how the cropper is like once you use it, and feel free to ask more questions :)

**Comment by kekland** [comment]
@talamaska Some updates:

- 3 is now almost ready - you can use `cropShapeFn` to specify a crop shape. However, there's still some work that needs to be done with the crop area normalizer (so that it supports any kind of a custom path), but the core functionality is ready.

- 4 - the Cupertino cropper will use the primary color from `CupertinoTheme` of the app. I will add a way to change any color in the cropper, but this will be done after the Material cropper is ready.

- 5 - added `enabledTransformations`

- 6 - This will also be done after the Material cropper is ready so I can evaluate what sort of widgets can be extracted to the `common` folder

**Comment by talamaska** [comment]
Hey, thanks for the update. I have subscribed to all events on repo. So I'll keep an eye. You can close this issue.
