### ISSUE TITLE
 Get address from an image

### ISSUE THREAD

**Issue by rodrigonepomuceno** [kekland/croppy#13]
How do I take an edited image and send it to my backend?
I cropped it, rotated it, etc. How do I get this modified image and send it to my backend? I didn't find how to do this in the package

**Comment by kekland** [comment]
Hi!

The package was designed specifically to be open-ended (the resulting image is `ui.Image`), so theoretically developers can do anything with that image (feed it to another different package, consume it in the UI, etc). However, it also makes it a bit less beginner-friendly.

I've just added a documentation on how you can save the contents of the crop result (i.e. the `ui.Image` object) to a local file in the latest version. You can find the markdown file here: https://github.com/kekland/croppy/blob/1.1.4/doc/saving-images.md

Let me know if it resolves your issues.

**Comment by rodrigonepomuceno** [comment]
Cool, it's clearer now.
Perhaps a suggestion would be to have a "friendly" method to make this save. But your explanation is clear and easy to understand.
Thanks for the feedback.

**Comment by rodrigonepomuceno** [comment]
Cool, it's clearer now.
Perhaps a suggestion would be to have a "friendly" method to make this save. But your explanation is clear and easy to understand.
Thanks for the feedback.

**Comment by kekland** [comment]
Will think if I can provide a `postProcessFn` to save the image to a file without having to write one manually.
