### ISSUE TITLE
Is it possible to add another locale and translations without doing it in the package source code?

### ISSUE THREAD

**Issue by longtimedeveloper** [kekland/croppy#24]
Hi,

Is it possible to add another locale and translations without doing it in the package source code?

I need to support another locale in my app but didn't want to download source code and use a local package if possible.

Thank you!

Karl

**Comment by kekland** [comment]
Hi!

Hope everything is going well for you. Yes, it's possible to do so. Please see https://github.com/kekland/croppy/blob/master/doc/localization.md and https://github.com/kekland/croppy/blob/master/example/lib/localization_override_example.dart for an example of how to do so.

If there are further questions feel free to reopen this issue.
