### ISSUE TITLE
HTML Build not working

### ISSUE THREAD

**Issue by Lykeosovandara** [kekland/croppy#26]
final bytesData =
          await result!.uiImage.toByteData(format: ImageByteFormat.png)
/// bytesdata == null (true)

**Comment by kekland** [comment]
Hi! Could you provide more information as to what is going wrong? Thanks a lot.

**Comment by kekland** [comment]
Could you please try to build the app in the latest version (1.2.0)? It includes WASM support so things might be fixed.

If the issue still perists, feel free to reopen this.
