### ISSUE TITLE
════════ Exception caught by gesture ═══════════════════════════════════════════ Invalid argument(s): Failed to load dynamic library 'libcroppy.so': dlopen failed: library "libcroppy.so" not found ════════════════════════════════════════════════════════════════════════════════

### ISSUE THREAD

**Issue by haleem13** [kekland/croppy#28]
bro i am facing this error while using any gesture. could you please help me as soon as possible? thanks yuou

════════ Exception caught by gesture ═══════════════════════════════════════════
Invalid argument(s): Failed to load dynamic library 'libcroppy.so': dlopen failed: library "libcroppy.so" not found
════════════════════════════════════════════════════════════════════════════════

**Comment by zalwan** [comment]
update your sdk or ndk, its work for me .

**Comment by kekland** [comment]
Hi! Please check whether this issue is reproducible on the newest version (with #31 merged). Feel free to reopen if the issues persist.
