### ISSUE TITLE
"Done" text color should be customizable

### ISSUE THREAD

**Issue by louislamlam** [kekland/croppy#29]
As the crop screen background color and `CupertinoTheme.of(context).primaryColor `are both black. The "Done" button is "invisible" as shown as screenCap.

![Simulator Screenshot - iPhone 15 Pro](https://github.com/kekland/croppy/assets/9133226/5d60f120-c9db-4cf8-9f60-f11818e6f0ff)

**Comment by dorklein** [comment]
+1. No easy way to customize the theme color

**Comment by talamaska** [comment]
please check if the solution proposed is solving your issue:
https://github.com/kekland/croppy/issues/33

**Comment by kekland** [comment]
Hi! Please see the latest version (1.2.0), and the following comment: https://github.com/kekland/croppy/issues/38#issuecomment-2241264485

If issues still persist, feel free to reopen this issue.
