### ISSUE TITLE
Wrong theme colors

### ISSUE THREAD

**Issue by talamaska** [kekland/croppy#33]
I checked the logic. It has flaws. 
First of you create a completely new dark theme from seed using the current active theme primary color, which might be a light theme primary color. Yes you set that's dark, but this seems to be broken when the primary color is dark.

I get the save button with my dark purple for light theme and dark text. 

![image](https://github.com/kekland/croppy/assets/299973/8832d31f-6350-43cd-a95e-d7e7f9b95e69)

So I copied that function of yours showMaterialImageCropper and wrapped the MaterialImageCropperPage with a real dark theme 
```dart
 builder: (context, controller) => Theme(
          data: darkTheme,
          child: MaterialImageCropperPage(
            heroTag: heroTag,
            controller: controller,
            shouldPopAfterCrop: shouldPopAfterCrop,
          ),
        ),
```

Typically buttons are lighter using lighter colors than light theme. Also the contrast of the text is ok, cause it is set onPrimary, onSecondary etc correctly. So I got correct themeed croppy now 

![image](https://github.com/kekland/croppy/assets/299973/3a67f6c9-7df3-4456-8b57-4e7ceb96f1e2)

My suggestion is to just create a theme extension for your MaterialImageCropperPage/CupertinoImageCropperPage
and give the possibly to alter colors from their theme configurations. Or avoid creating your own theme on top of wrong active theme colors, or at least give us the possibility to set primaryColor, secondaryColor, BackgroundColor, markerColor, text color for secondary and for primary buttons.

**Comment by kekland** [comment]
Hi, thanks for noticing this! Yes, seems like the primary color can be darker on light themes, which I've completely overlooked. I've added a patch in the latest version and updated the code for material theme generation.

Feel free to reopen if issues still persist.
