### ISSUE TITLE
Allowed aspect ratio is not applied when reset button is clicked

### ISSUE THREAD

**Issue by khaven** [kekland/croppy#37]
I've initialized croppy with just 1:1 aspect ratio. I want to force users to just crop in 1:1 aspect ratio. But when reset button is clicked the 
crop aspect ratio is also gets reset and users able to crop without respecting the allowed aspect ratios.

**Comment by talamaska** [comment]
this is the same as https://github.com/kekland/croppy/issues/18

check my PR, use my fork if you want

**Comment by kekland** [comment]
Closing this, seems to be a duplicate of #18. A fix will be deployed in the next release
