### ISSUE TITLE
Hi! Does croppy preserve the exif data of the edited image?

### ISSUE THREAD

**Issue by Yuvi-raj-P** [kekland/croppy#40]
Hello was just wondering if this library preserves the meta or the exif data of an image after edited

**Comment by kekland** [comment]
Hi! 

No, the image is returned as raw byte data (ui.Image). However, you can convert it to jpg and manually add exif tags later

**Comment by Yuvi-raj-P** [comment]
How could you add exif tags? Any packages that you use?

**Comment by kekland** [comment]
Not sure, but this is not in the scope of this package. There should be a tool or package available

**Comment by Yuvi-raj-P** [comment]
Alright thank you, I was just wondering I tried many packages nothing worked for writing the exif information, I never done it so I don't know about it. However this is a wonderful product thanks for releasing this. I will be using this package in future for Immich https://github.com/immich-app/immich
