### ISSUE TITLE
How to get the cropped image absolute path

### ISSUE THREAD

**Issue by OICQ469** [kekland/croppy#47]
![WechatIMG909](https://github.com/user-attachments/assets/402ed2c1-fe39-4310-8b98-f6fe57eb4a17)

**Comment by OICQ469** [comment]
I need to upload the cropped image @kekland

**Comment by kekland** [comment]
Please see https://github.com/kekland/croppy/blob/master/doc%2Fsaving-images.md

**Comment by OICQ469** [comment]
> 请参阅https://github.com/kekland/croppy/blob/master/doc%2Fsaving-images.md

thank
