### ISSUE TITLE
Can you allow Dart SDK 2.19.2?

### ISSUE THREAD

**Issue by mralbertchen** [kekland/croppy#5]
Currently the pubspec is set to >= 3.0.0 but our repo is not ready to update yet. Is it possible for you to lower it?

**Comment by kekland** [comment]
Hi!

The work on this package began when Dart 3 was already stable, so it was chosen as the minimum constraint.

I'll try and see in the coming days if it's possible to make the constraint lower - assuming that the repo isn't using any Dart 3-specific features.

**Comment by kekland** [comment]
@mralbertchen unfortunately, there's a lot of places in the code that are already using records; therefore there's no straightforward way to reduce the constraint except for changing that code.

**Comment by kekland** [comment]
Closing this as no potential solutions exist at the moment
