### ISSUE TITLE
How to create a fixed square, cropping box

### ISSUE THREAD

**Issue by OICQ469** [kekland/croppy#50]
![WechatIMG911](https://github.com/user-attachments/assets/93daf0a9-6ddc-41f4-9ffd-a880b2c30c2c)

How to create a fixed square, cropping box @kekland

**Comment by kekland** [comment]
Please read the documentation at https://github.com/kekland/croppy/blob/master/doc%2Fdoc.md. To get a square, you need to constrain the aspect ratio.
