### ISSUE TITLE
How to create a custom crop shape

### ISSUE THREAD

**Issue by Adrien30starly** [kekland/croppy#52]
Thank you for this wonderful package. I am a bit confused on how to create my own crop shape actually. The shape I want for the croper is as shown in the uploaded svg. Is this possible and if so how can I achieve this shape. Thank you in advance.

[avatar1.zip](https://github.com/user-attachments/files/17556659/avatar1.zip)

**Comment by kekland** [comment]
Hi! You can see the star crop shape function as an example: https://github.com/kekland/croppy/blob/06e84b3597571fa1f8f6818f604d80f376bf44fc/lib/src/model/crop_shape.dart#L142.

It's not possible to use an SVG directly, but you should be able to turn the SVG `<g>` elements to the corresponding operations.

Feel free to reopen if any more issues occur.
