### ISSUE TITLE
Rotating an image with a forced aspect ratio inverts the aspect ratio

### ISSUE THREAD

**Issue by maRci002** [kekland/croppy#7]
Let's say my `allowedAspectRatios` is `16/9`. Whenever I rotate the image, the aspect ratio is inverted, which means that when I export the image, it becomes a `9/16` aspect ratio.

_Note_: If I start to pan the crop area, it will reset itself to the expected `16/9` aspect ratio.

https://github.com/kekland/croppy/assets/8436039/c5509c1f-10be-4cc8-a4af-6f6de200d0a3

**Comment by kekland** [comment]
Hi, thanks for the report! Will try to fix today - if not, then during this week.

**Comment by maRci002** [comment]
> Hi, thanks for the report! Will try to fix today - if not, then during this week.

Thank you very much, it's not urgent for me, do it when you have free time.

**Comment by kekland** [comment]
Should now be resolved with version 0.2.5.
