### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jkoenig134** [kekland/croppy#8]
As stated in the Readme Localization is in progress.

I really love the look and feel of croppy but the missing Localization support is a dealbreaker.

**Comment by kekland** [comment]
Hi! This is also currently work-in-progress. I can only provide localizations for English, Kazakh, and Russian, but it would be great if you can also add the localization files in your language too.

There's only like 10 strings to localize. I'll keep you posted when this will land in `main` - probably in a couple of hours

**Comment by jkoenig134** [comment]
I can additionally provide german. It would also be cool if I could add translations programatically.

**Comment by jkoenig134** [comment]
Additionally, any ETA on when this could land?

**Comment by kekland** [comment]
I'm currently planning to stick to https://docs.flutter.dev/ui/accessibility-and-localization/internationalization (and use `.arb` files for localization). I think it would be the best option in the long term.

As for the ETA - couple of hours

**Comment by kekland** [comment]
Nvm, don't think generating `.arb`s would work. I'll just make an abstract class that contains the strings

**Comment by kekland** [comment]
Hey, just added the groundwork for localization in https://github.com/kekland/croppy/commit/4c732e8fb937635de0d4fbe1ba9b13016a6ef711. Please see localization documentation in https://github.com/kekland/croppy/blob/4c732e8fb937635de0d4fbe1ba9b13016a6ef711/doc/localization.md to add your own languages, and thanks again for helping to localize Croppy! :)

Let me know if there's anything I need to change or if something is unclear
